version: '3'

services:
    db:
        image: postgres:12-alpine
        environment:
            POSTGRES_USER: posthog
            POSTGRES_DB: posthog
            POSTGRES_PASSWORD: posthog
        ports:
            - '5439:5432'
    redis:
        image: 'redis:alpine'
        ports:
            - '6379:6379'
    clickhouse:
        image: yandex/clickhouse-server
        depends_on:
            - kafka
        ports:
            - '8123:8123'
            - '9000:9000'
            - '9440:9440'
            - '9009:9009'
        volumes:
            - ./idl:/idl
            - ../docker/clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - ../docker/clickhouse/config.xml:/etc/clickhouse-server/config.xml
    zookeeper:
        image: wurstmeister/zookeeper
    kafka:
        image: wurstmeister/kafka
        depends_on:
            - zookeeper
        ports:
            - '9092:9092'
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    worker: &worker
        build:
            context: ../
            dockerfile: dev.Dockerfile
        command: ./bin/docker-worker-celery --with-scheduler
        volumes:
            - ..:/code
        environment:
            DATABASE_URL: 'postgres://posthog:posthog@db:5432/posthog'
            CLICKHOUSE_HOST: 'clickhouse'
            CLICKHOUSE_DATABASE: 'posthog'
            CLICKHOUSE_SECURE: 'false'
            CLICKHOUSE_VERIFY: 'false'
            KAFKA_URL: 'kafka://kafka'
            REDIS_URL: 'redis://redis:6379/'
            SECRET_KEY: 'alsdfjiosdajfklalsdjkf'
            DEBUG: 'true'
            PRIMARY_DB: 'clickhouse'
            PGHOST: db
            PGUSER: posthog
            PGPASSWORD: posthog
        depends_on:
            - db
            - redis
            - clickhouse
            - kafka
        links:
            - db:db
            - redis:redis
            - clickhouse:clickhouse
            - kafka:kafka
    web:
        <<: *worker
        command: ./ee/bin/docker-ch-dev-web
        ports:
            - '8000:8000'
            - '8234:8234'
    plugins:
        image: posthog/plugin-server:latest
        restart: on-failure
        environment:
            DATABASE_URL: 'postgres://posthog:posthog@db:5432/posthog'
            KAFKA_ENABLED: 'true'
            KAFKA_HOSTS: 'kafka:9092'
            REDIS_URL: 'redis://redis:6379/'
            CLICKHOUSE_HOST: 'clickhouse'
        depends_on:
            - db
            - redis
            - clickhouse
            - kafka
        links:
            - db:db
            - redis:redis
            - clickhouse:clickhouse
            - kafka:kafka
    chbk:
        image: alexakulov/clickhouse-backup
        command: server
        ports:
            - '7171:7171'
        environment:
            API_LISTEN: '0.0.0.0:7171'
            REMOTE_STORAGE: 's3'
            LOG_LEVEL: 'debug'
            CLICKHOUSE_HOST: 'clickhouse'
            S3_ENDPOINT: 'http://minio:9090'
            S3_ACCESS_KEY: 'AKIAIOSFODNN7EXAMPLE'
            S3_SECRET_KEY: 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY'
            S3_BUCKET: 'posthog-ch-backups-test'
            S3_COMPRESSION_LEVEL: '1'
            S3_COMPRESSION_FORMAT: 'tar'
            S3_ACL: 'private'
            S3_FORCE_PATH_STYLE: 'true'
            S3_PATH: 'backup'
            S3_DISABLE_SSL: 'true'
        depends_on:
            - clickhouse
            - minio
    minio:
        image: minio/minio
        command: server --address :9090 /data
        ports:
            - '9090:9090'
        volumes:
            - ./s3data:/data
        environment:
            MINIO_ROOT_USER: 'AKIAIOSFODNN7EXAMPLE'
            MINIO_ROOT_PASSWORD: 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY'
